name: 批量保活进程

on:
  schedule:
    # 使用cron表达式定义任务运行的时间
    # 每天UTC时间0:15和10:45分别触发，分别对应北京时间8:15和18:45
    - cron: '15 0 * * *'  # UTC时间0:15，对应北京时间8:15
    - cron: '45 10 * * *'  # UTC时间10:45，对应北京时间18:45
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo apt-get install sshpass
          sudo apt-get install jq

      - name: 登录各个serv00并执行保活脚本
        env:
          HOSTS_JSON: ${{ secrets.HOSTS_JSON }}
          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          TELEGRAM_USERID: ${{secrets.TELEGRAM_USERID}}
          WXSENDKEY: ${{secrets.WXSENDKEY}}
          SENDTYPE: ${{secrets.SENDTYPE}}
        run: |
          chmod +x ./revive.sh
          ./revive.sh
